// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 同步问候。`#[frb(sync)]` 让 Dart 侧得到一个同步函数（无需 await）。
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// 异步加法：默认（不加 `sync`）即异步——Dart 侧 `await add(a: 2, b: 40)`，
/// Rust 在独立线程池执行，不卡 Flutter UI 线程。演示 frb 的 async 桥接。
Future<int> add({required int a, required int b}) =>
    RustLib.instance.api.crateApiSimpleAdd(a: a, b: b);

/// 返回 `Result`：除零返回 `Err`，在 Dart 侧表现为抛出的异常。
/// 演示「Rust 错误 → Dart 异常」的跨界映射（对照 UniFFI 的受检异常）。
Future<double> divide({required double a, required double b}) =>
    RustLib.instance.api.crateApiSimpleDivide(a: a, b: b);
